# Numpy

Numpy is a powerful Python library for numerical computing. It provides support for multidimensional arrays, mathematical functions, random number generation, linear algebra operations, and much more. NumPy is widely used in scientific computing, data analysis, and machine learning.

Key features of the Numpy library include:

* **Creating Numpy Arrays:**
Numpy's primary data structure is the ndarray, a multidimensional array object. You can create Numpy arrays from Python lists or using Numpy's array creation functions.

In [1]:
import numpy as np

# Creating a 1D NumPy array from a Python list
arr1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D NumPy array from a list of lists
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr1d)
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* **Basic Array Operations:**
Numpy provides functions and operators for basic array operations such as element-wise arithmetic operations, array indexing, slicing, and reshaping.

In [2]:
# Element-wise arithmetic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 * arr2)

# Array indexing and slicing
print(arr2d[0, 1])  # Accessing element at row 0, column 1
print(arr2d[:, 1])  # Accessing all elements in column 1

# Reshaping arrays
arr3d = np.arange(12).reshape((2, 2, 3))
print(arr3d)

[5 7 9]
[ 4 10 18]
2
[2 5 8]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


* **Mathematical Functions:**
Numpy provides a wide range of mathematical functions that operate element-wise on arrays, such as sin, cos, exp, log, etc.

In [3]:
# Computing trigonometric functions
arr = np.array([0, np.pi/2, np.pi])
print(np.sin(arr))
print(np.cos(arr))

# Computing exponential and logarithmic functions
print(np.exp(arr))
print(np.log(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[      -inf 0.45158271 1.14472989]


/tmp/ipykernel_37265/2324231433.py:8: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


* **Random Number Generation:**
Numpy provides functions for generating random numbers from various probability distributions.

In [4]:
# Generating random numbers from a uniform distribution
rand_arr = np.random.rand(3, 3)
print(rand_arr)

# Generating random integers between a specified range
rand_int = np.random.randint(1, 10, size=(3, 3))
print(rand_int)

[[0.46235193 0.18655192 0.01109501]
 [0.94890837 0.58829727 0.61706833]
 [0.82129912 0.75495716 0.85936123]]
[[1 2 9]
 [7 6 2]
 [3 5 4]]


* **Linear Algebra Operations:**
Numpy provides functions for performing various linear algebra operations, such as matrix multiplication, matrix inversion, eigenvalue decomposition, etc.

In [5]:
# Matrix multiplication
A = np.array([[0, 2], [3, 4]])
B = np.array([[4, 6], [7, 8]])
print(np.dot(A, B))

# Matrix inversion
A_inv = np.linalg.inv(A)
print(A_inv)

[[14 16]
 [40 50]]
[[-0.66666667  0.33333333]
 [ 0.5         0.        ]]


Numpy's extensive capabilities make it a fundamental library for numerical computing in Python, enabling efficient and scalable operations on arrays and matrices.